In [32]:
import pandas as pd

In [33]:
newdf=pd.read_csv("survey_results_public.csv")

In [34]:
filt=newdf['Country'].str.contains('vakia')

In [35]:
newdf.loc[filt,'Country']

0        Slovakia
135      Slovakia
259      Slovakia
1721     Slovakia
1928     Slovakia
           ...
80860    Slovakia
80979    Slovakia
81779    Slovakia
82209    Slovakia
82442    Slovakia
Name: Country, Length: 252, dtype: object

In [36]:
newdf['Trans']=newdf['Trans'].replace({'Yes':True,'No':False})
#newdf['Trans'].map({'Yes':True,'No':False})

In [37]:
kgf=newdf['Country']=='Slovakia'
kgf

0         True
1        False
2        False
3        False
4        False
         ...
83434    False
83435    False
83436    False
83437    False
83438    False
Name: Country, Length: 83439, dtype: bool

In [38]:
newdf.drop(index=newdf[kgf].index)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,False,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,False,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,False,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,False,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
5,6,I am a student who is learning to code,"Student, part-time",United States of America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Prefer not to say,False,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,25-34 years old,Man,False,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83435,83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,18-24 years old,Man,False,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83436,83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,25-34 years old,Man,False,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83437,83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,25-34 years old,Man,False,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83438,83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,...,18-24 years old,Man,False,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [39]:
newdf.sort_values(by=['Country'],ascending=True,inplace=True)

In [40]:
newdf.sort_index(inplace=True)

In [41]:
newdf['ConvertedCompYearly'].nlargest(6)

66910    45241312.0
65399    30468516.0
40586    21822250.0
28791    20000000.0
12700    19200000.0
9608     17500000.0
Name: ConvertedCompYearly, dtype: float64

In [42]:
newdf.nlargest(10,'ConvertedCompYearly')

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
66910,66911,I am a developer by profession,I prefer not to say,Belgium,NaN,NaN,Primary/elementary school,55 - 64 years,Books / Physical media,1,...,55-64 years old,NaN,True,NaN,Black or of African descent,I am blind / have difficulty seeing,I have a concentration and/or memory disorder ...,Too short,NaN,45241312.0
65399,65400,I am a developer by profession,Employed full-time,Afghanistan,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25 - 34 years,Online Courses or Certification,7,...,35-44 years old,"Man;Non-binary, genderqueer, or gender non-con...",True,Bisexual;Prefer to self-describe:;Gay or Lesbi...,South Asian;Hispanic or Latino/a/x;Black or of...,I am unable to / find it difficult to walk or ...,I have a mood or emotional disorder (e.g. depr...,Too short,Difficult,30468516.0
40586,40587,I am a developer by profession,Employed full-time,United States of America,California,NaN,Some college/university study without earning ...,Younger than 5 years,"Other online resources (ex: videos, blogs, etc...",37,...,35-44 years old,Man,False,Bisexual,White or of European descent,I am blind / have difficulty seeing,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,21822250.0
28791,28792,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",35 - 44 years,Coding Bootcamp;Other online resources (ex: vi...,11,...,35-44 years old,Man,False,Prefer not to say,Prefer not to say,Prefer not to say,None of the above,Appropriate in length,Easy,20000000.0
12700,12701,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25 - 34 years,Online Forum,5,...,35-44 years old,Man,False,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,19200000.0
9608,9609,"I am not primarily a developer, but I write co...",Employed full-time,United States of America,New York,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,School,25,...,35-44 years old,Man,False,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,17500000.0
5305,5306,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United States of America,New Jersey,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,Friend or family member;Books / Physical media,25,...,35-44 years old,Man,False,NaN,White or of European descent,None of the above,None of the above,Too long,Easy,15000000.0
12903,12904,I am a developer by profession,Employed full-time,Serbia,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,18-24 years old,Man,False,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too long,Neither easy nor difficult,14411628.0
66488,66489,I am a developer by profession,Employed full-time,United States of America,Washington,NaN,Some college/university study without earning ...,18 - 24 years,School;Online Courses or Certification;Books /...,5,...,25-34 years old,Man,False,Straight / Heterosexual,Prefer not to say,Prefer not to say,Prefer not to say,Appropriate in length,Easy,12750000.0
7205,7206,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United States of America,South Carolina,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5 - 10 years,"Other online resources (ex: videos, blogs, etc...",30,...,35-44 years old,Man,False,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,12500000.0

In [43]:
newdf=newdf.rename(columns={'ConvertedCompYearly':'Income'})

In [44]:
newdf['Sexuality'].value_counts()

Straight / Heterosexual                                                           61094
Prefer not to say                                                                  4783
Bisexual                                                                           2879
Gay or Lesbian                                                                     1367
Prefer to self-describe:                                                           1258
Straight / Heterosexual;Bisexual                                                    492
Queer                                                                               376
Bisexual;Queer                                                                      273
Straight / Heterosexual;Prefer to self-describe:                                    225
Gay or Lesbian;Queer                                                                149
Straight / Heterosexual;Queer                                                        78
Bisexual;Gay or Lesbian                                                              71
Prefer to self-describe:;Queer                                                       61
Bisexual;Gay or Lesbian;Queer                                                        49
Bisexual;Prefer to self-describe:                                                    36
Bisexual;Prefer to self-describe:;Queer                                              26
Straight / Heterosexual;Bisexual;Prefer to self-describe:;Gay or Lesbian;Queer       22
Straight / Heterosexual;Gay or Lesbian                                               21
Straight / Heterosexual;Bisexual;Gay or Lesbian;Queer                                21
Straight / Heterosexual;Bisexual;Gay or Lesbian                                      18
Straight / Heterosexual;Bisexual;Queer                                               15
Prefer to self-describe:;Gay or Lesbian;Queer                                        14
Straight / Heterosexual;Bisexual;Prefer to self-describe:                            11
Bisexual;Prefer to self-describe:;Gay or Lesbian;Queer                               10
Straight / Heterosexual;Prefer to self-describe:;Queer                                5
Prefer to self-describe:;Gay or Lesbian                                               5
Bisexual;Prefer to self-describe:;Gay or Lesbian                                      3
Straight / Heterosexual;Bisexual;Prefer to self-describe:;Gay or Lesbian              2
Straight / Heterosexual;Gay or Lesbian;Queer                                          1
Straight / Heterosexual;Bisexual;Prefer to self-describe:;Queer                       1
Name: Sexuality, dtype: int64

In [45]:
country=newdf.groupby(['Country'])

In [46]:
country['Income'].agg(['max','mean'])

                                             max          mean
Country
Afghanistan                           30468516.0  2.794748e+06
Albania                                 692042.0  4.499814e+04
Algeria                                  48550.0  1.446114e+04
Andorra                                 146981.0  8.928200e+04
Angola                                   96000.0  2.155680e+04
...                                          ...           ...
Venezuela, Bolivarian Republic of...    229596.0  2.246505e+04
Viet Nam                                258744.0  1.995289e+04
Yemen                                    19176.0  5.628667e+03
Zambia                                  105000.0  1.991491e+04
Zimbabwe                                 36000.0  1.141477e+04

[181 rows x 2 columns]

In [47]:
country['Income'].agg(['median','mean']).loc['India']

median    14748.000000
mean      42522.583464
Name: India, dtype: float64

In [48]:
respondant=newdf['Country'].value_counts()

In [49]:
respondant

United States of America                                15288
India                                                   10511
Germany                                                  5625
United Kingdom of Great Britain and Northern Ireland     4475
Canada                                                   3012
                                                        ...
Saint Kitts and Nevis                                       1
Dominica                                                    1
Saint Vincent and the Grenadines                            1
Tuvalu                                                      1
Papua New Guinea                                            1
Name: Country, Length: 181, dtype: int64

In [50]:
newdf['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20', '8', '19', '5', 'Less than 1 year', '22',
       '2', '1', '34', '21', '13', '25', '24', '30', '31', '18', '38',
       'More than 50 years', '27', '41', '42', '35', '23', '28', '11',
       '37', '44', '43', '36', '33', '45', '29', '50', '46', '32', '47',
       '49', '48'], dtype=object)

In [51]:
newdf['YearsCode']=newdf['YearsCode'].replace('Less than 1 year',0)

In [52]:
newdf['YearsCode']=newdf['YearsCode'].replace('More than 50 years',51)

In [53]:
newdf['YearsCode']=newdf['YearsCode'].astype(float)

In [54]:
newdf['YearsCode'].mean()

12.338200169032717